Enhance Users controller
Open-MBEE/exec-mms pull request #173
Opened 2021-09-20 22:35 UTC by Enquier

This is a proposed fix for #172 which allows non-admins to lookup users. It also adds a query parameter which to allow search for a specific username.

2021-09-21 21:04 UTC, HuiJun requested changes

2021-09-21 21:04 UTC, HuiJun commented on ldap/src/main/java/org/openmbee/mms/ldap/LdapSecurityConfig.java
> +        saveUser.setAdmin(false);
These will need to be considered. We don't want to modify an admin user and have this logic convert them to a regular user and we don't want to enable a disabled user on modification either.

2021-09-21 21:04 UTC, HuiJun commented on build.gradle
> +
Why is this?

2021-09-22 18:59 UTC, Enquier commented on ldap/src/main/java/org/openmbee/mms/ldap/LdapSecurityConfig.java
> +        saveUser.setAdmin(false);
Fixed. Moved over to the create side only

2021-09-22 19:00 UTC, Enquier commented on build.gradle
> +
Adds ability to run MMS as a server from gradle directly. For rapid development without generating a new docker container for each run

2021-09-22 19:28 UTC, HuiJun requested changes

2021-09-22 19:28 UTC, HuiJun commented on build.gradle
> +
MMS already has the ability to run from gradle directly. It's called ./gradlew bootRun.

2021-10-05 16:37 UTC, HuiJun approved these changes

2021-10-06 00:44 UTC, merged