Release/4.0.19
Open-MBEE/exec-mms pull request #252
Opened 2023-12-05 20:55 UTC by HuiJun

2023-12-06 02:19 UTC, dlamoris requested changes
check the storage/artifact aws lib version to see if it works for eks service account

also readthedocs needs a yaml file in root now to build, https://blog.readthedocs.com/migrate-configuration-v2/

also take out the lgtm badge and fix the circleci link in readme

2023-12-12 18:04 UTC, HuiJun commented
The minimum version for AWS SDK for service accounts, I believe is `1.11.704` and we are currently on `1.11.874`, so we should be good there.

2023-12-12 21:38 UTC, dlamoris commented on .circleci/config.yml
> +        - build_and_test
i believe this will also require the filter tags to be present or else the release won't run, had something similar happen in the flexo repos

2023-12-12 21:38 UTC, dlamoris commented on .circleci/config.yml
> +              context:
we dont' actually need dockerhub here since we're not pushing to docker, may want it in mmsri

2023-12-13 01:27 UTC, dlamoris approved these changes

2023-12-13 01:27 UTC, merged