Feature/mms 88
Open-MBEE/exec-mms pull request #71
Opened 2020-05-01 15:34 UTC by HuiJun

2020-05-01 19:16 UTC, dlamoris requested changes

2020-05-01 19:16 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/services/DefaultProjectService.java
> +            projectIndex.update(project);
don't think project has docId set here

2020-05-01 19:16 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/controllers/projects/ProjectsController.java
> +                }
need to update single project get below

2020-05-01 19:16 UTC, dlamoris commented on elastic/src/main/java/org/openmbee/sdvc/elastic/ProjectElasticImpl.java
> +        return super.getIndex() + "_metadata";
super.getIndex depends on context projectid being set, check if the project endpoints set that before getting here

2020-05-01 19:16 UTC, dlamoris commented on elastic/src/main/java/org/openmbee/sdvc/elastic/ProjectElasticImpl.java
> +            nodeIndex.mapping(getMetadataMapping(), XContentType.JSON);
should be metadataIndex

2020-05-01 19:16 UTC, dlamoris commented on elastic/src/main/java/org/openmbee/sdvc/elastic/ProjectElasticImpl.java
> +            nodeIndex.mapping(getMetadataMapping(), XContentType.JSON);
also i don't see the metadata mapping commited?

2020-05-01 23:01 UTC, HuiJun commented on crud/src/main/java/org/openmbee/sdvc/crud/services/DefaultProjectService.java
> +            projectIndex.update(project);
should be set on line 75

2020-05-01 23:01 UTC, HuiJun commented on elastic/src/main/java/org/openmbee/sdvc/elastic/ProjectElasticImpl.java
> +            nodeIndex.mapping(getMetadataMapping(), XContentType.JSON);
outdated

2020-05-02 00:06 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/services/DefaultProjectService.java
> +            projectIndex.update(project);
that's in the create function though?

2020-05-02 07:16 UTC, merged