added create and delete methods for indices, these should be moved in…
Open-MBEE/exec-mms pull request #8
Opened 2018-12-13 00:53 UTC by lauraerinmann

…to a refactor for CORE.

2018-12-14 04:01 UTC, HuiJun requested changes

2018-12-14 04:01 UTC, HuiJun commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/BaseElasticDAOImpl.java
> +import java.util.Map.Entry;
Not a biggie, but I'd rather just use Map.Entry rather than importing it and using it as Entry. We already imported Map.

2018-12-14 04:01 UTC, HuiJun commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/ProjectIndex.java
> +
We should also maybe add an update method.

2018-12-14 04:01 UTC, HuiJun commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/ProjectElasticImpl.java
> +    @Override
Are these overriding anything?

2018-12-14 04:01 UTC, HuiJun commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/commit/CommitElasticDAOImpl.java
> +        return null;
Let's start adding TODOs to these so we can find them easier.

2018-12-19 17:54 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/BaseElasticDAOImpl.java
> +            bulkIndex.add(new DeleteRequest(index, null, json.getId()));
json.getIndexId() instead of getId()

2018-12-19 17:55 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/BaseElasticDAOImpl.java
> +            bulkIndex.add(new IndexRequest((index)).source(json));
IndexRequest needs type and id param, add "_doc" and json.getIndexId()

2018-12-19 17:56 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/BaseElasticDAOImpl.java
> +        client.index(new IndexRequest(index).source(json), RequestOptions.DEFAULT);
add "_doc" and json.getIndexId() to IndexRequest

2018-12-19 17:57 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/BaseElasticDAOImpl.java
> +        client.delete(new DeleteRequest(index, null, indexId), RequestOptions.DEFAULT);
i think all the type arguments still needs an actual type, elastic suggests just use "_doc"

2018-12-19 17:58 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/ProjectElasticImpl.java
> +        commitIndex.mapping(getCommitMapAsString(), XContentType.JSON);
needs the type, use "_doc" as first argument

2018-12-19 17:59 UTC, dlamoris commented on crud/src/main/java/org/openmbee/sdvc/crud/repositories/ProjectElasticImpl.java
> +        return "{\"properties\":{\"added\":{\"properties\":{\"id\":{\"type\":\"keyword\"},\"_indexId\":{\"type\":\"keyword\"},\"type\":{\"type\":\"keyword\"}}},\"updated\":{\"properties\":{\"id\":{\"
add {\"_doc\": to the front and } to the back

2018-12-19 23:45 UTC, HuiJun approved these changes

2018-12-19 23:48 UTC, merged