Updated for view editor compatibility
Open-MBEE/exec-mms pull request #82
Opened 2020-07-02 18:32 UTC by BA-MBSE

* Added search pagination and consistent ordering
* Added /checkAuth endpoint
* Added field wildcard

Updated ElasticSearchService to intelligently choose query methods based on field mapping types

2020-07-16 17:14 UTC, HuiJun commented on authenticator/src/main/java/org/openmbee/sdvc/authenticator/controllers/AuthenticationController.java
> +            if (username != null && username != "anonymousUser") {
Is "anonymousUser" a standard user that can be created by some dependency? Or is it a user that will be required?

2020-07-20 21:51 UTC, dlamoris commented on authenticator/src/main/java/org/openmbee/sdvc/authenticator/controllers/AuthenticationController.java
> +            if (username != null && username != "anonymousUser") {
i think that's what spring puts in when a user isn't authenticated (authenticated anonymously) 
maybe a better way would be to just check for Authentication object instance of AnonymousAuthenticationToken

2020-07-20 22:04 UTC, dlamoris requested changes
the check auth can be simplified (see MethodSecurityService), otherwise looks good

2020-07-28 14:49 UTC, BA-MBSE commented on authenticator/src/main/java/org/openmbee/sdvc/authenticator/controllers/AuthenticationController.java
> +            if (username != null && username != "anonymousUser") {
Simplified as requested

2020-07-29 20:36 UTC, dlamoris approved these changes

2020-07-29 20:36 UTC, merged