Adding new bulk processor for elasticsearch implementation
Open-MBEE/exec-mms pull request #95
Opened 2020-09-03 23:09 UTC by HuiJun

2020-09-16 19:57 UTC, dlamoris requested changes

2020-09-16 19:57 UTC, dlamoris commented on gradle.properties
> +elasticVersion=7.9.0
is there a 7.7.x version? the highest on aws right now is 7.7 and the client are forward but not backwards compatible

2020-09-16 19:57 UTC, dlamoris commented on twc/src/main/java/org/openmbee/sdvc/twc/services/TwcRevisionMmsCommitMapService.java
> +        if (revisionId.isEmpty()) {
should check for null first also

2020-09-16 19:57 UTC, dlamoris commented on elastic/src/main/java/org/openmbee/sdvc/elastic/BaseElasticDAOImpl.java
> +                public void afterBulk(long executionId, BulkRequest request, BulkResponse response) {
should log any failures for now

2020-09-16 19:57 UTC, dlamoris commented on elastic/src/main/java/org/openmbee/sdvc/elastic/BaseElasticDAOImpl.java
> +    private final Logger logger = LogManager.getLogger(getClass());
use slf4j LoggerFactory.getLogger(getClass())

2020-09-16 19:57 UTC, dlamoris commented on example/example.gradle
> -        project(':twc'),
take out ldap too

2020-09-18 21:41 UTC, HuiJun commented on example/example.gradle
> -        project(':twc'),
done

2020-09-18 21:43 UTC, dlamoris commented on twc/src/main/java/org/openmbee/sdvc/twc/services/TwcRevisionMmsCommitMapService.java
> +        if (revisionId != null && revisionId.isEmpty()) {
should be == null ||

2020-09-18 21:51 UTC, dlamoris approved these changes

2020-09-18 21:53 UTC, merged